import {
  Apellido,
  BalanceGeneral,
  CargoEmpleado,
  CategoriaProducto,
  Cedula,
  Cuenta,
  Descripcion,
  DeudaCliente,
  Dinero,
  Direccion,
  Email,
  FechaActualizacion,
  FechaCreacion,
  FechaIngresos,
  FechaIngresosEmpleado,
  HistorialCompraCliente,
  HistorialDeCaja,
  HorarioApertura,
  HorarioCierre,
  MargenGanancias,
  MetodosPago,
  Movil,
  Nombre,
  NombreProducto,
  PrecioProducto,
  ProductosSuministrado,
  Propietario,
  RolUsuario,
  SalarioEmpleado,
  SitioWeb,
  StockMaximo,
  StockMinimo,
  TBussines,
  TipoCliente,
  Tipos,
  TotalGastos,
  TotalIngresos,
  Trabajadores,
  Unidad,
  VentasMensuales,
} from "./FormBusines";

export const formulariosDisponibles = [
  { id: "Propietario", nombre: "Propietario", campos: Propietario },
  { id: "Direccion", nombre: "Dirección", campos: Direccion },
  { id: "Email", nombre: "Correo Electrónico", campos: Email },
  {
    id: "FechaCreacion",
    nombre: "Fecha",
    campos: FechaCreacion,
  },
  { id: "Descripcion", nombre: "Descripción", campos: Descripcion },
  {
    id: "HorarioApertura",
    nombre: "Horario de Apertura",
    campos: HorarioApertura,
  },
  {
    id: "HorarioCierre",
    nombre: "Horario de Cierre",
    campos: HorarioCierre,
  },

  { id: "SitioWeb", nombre: "Sitio Web", campos: SitioWeb },
  {
    id: "Trabajadores",
    nombre: "Cantidad de Trabajadores",
    campos: Trabajadores,
  },
  {
    id: "CargoEmpleado",
    nombre: "Cargo del Empleado",
    campos: CargoEmpleado,
  },
  { id: "SalarioEmpleado", nombre: "Salario", campos: SalarioEmpleado },
  {
    id: "FechaIngresosEmpleado",
    nombre: "Fecha de Ingreso del Empleado",
    campos: FechaIngresosEmpleado,
  },
  { id: "MovilEmpleado", nombre: "Móvil o Teléfono", campos: Movil },
  {
    id: "RolUsuario",
    nombre: "Rol del Usuario / Empleado",
    campos: RolUsuario,
  },
  { id: "Nombre", nombre: "Nombre", campos: Nombre },
  { id: "Apellido", nombre: "Apellido", campos: Apellido },
  { id: "Cedula", nombre: "Cédula del Cliente", campos: Cedula },
  { id: "TipoCliente", nombre: "Tipo de Cliente", campos: TipoCliente },
  {
    id: "HistorialCompraCliente",
    nombre: "Historial de Compras",
    campos: HistorialCompraCliente,
  },
  { id: "DeudaCliente", nombre: "Deuda del Cliente", campos: DeudaCliente },
  {
    id: "NombreProducto",
    nombre: "Nombre del Producto",
    campos: NombreProducto,
  },
  {
    id: "CategoriaProducto",
    nombre: "Categoría del Producto",
    campos: CategoriaProducto,
  },
  {
    id: "PrecioProducto",
    nombre: "Precio del Producto",
    campos: PrecioProducto,
  },
  { id: "Unidad", nombre: "Unidad de Medida", campos: Unidad },
  { id: "StockMaximo", nombre: "Stock Máximo", campos: StockMaximo },
  { id: "StockMinimo", nombre: "Stock Mínimo", campos: StockMinimo },
  {
    id: "FechaIngresos",
    nombre: "Fecha de Ingreso del Producto",
    campos: FechaIngresos,
  },
  {
    id: "FechaActualizacion",
    nombre: "Fecha de Actualización",
    campos: FechaActualizacion,
  },
  {
    id: "ProductosSuministrado",
    nombre: "Productos Suministrados",
    campos: ProductosSuministrado,
  },
  { id: "MetodosPago", nombre: "Métodos de Pago", campos: MetodosPago },
  { id: "Dinero", nombre: "Dinero Disponible", campos: Dinero },
  { id: "Cuenta", nombre: "Cuenta Bancaria", campos: Cuenta },
  { id: "TBussines", nombre: "Tipo de Empresa", campos: TBussines },
  { id: "Tipos", nombre: "Tipos de Operaciones", campos: Tipos },
  {
    id: "TotalIngresos",
    nombre: "Total de Ingresos",
    campos: TotalIngresos,
  },
  { id: "TotalGastos", nombre: "Total de Gastos", campos: TotalGastos },
  {
    id: "BalanceGeneral",
    nombre: "Balance General",
    campos: BalanceGeneral,
  },
  {
    id: "VentasMensuales",
    nombre: "Ventas Mensuales",
    campos: VentasMensuales,
  },
  {
    id: "MargenGanancias",
    nombre: "Margen de Ganancias",
    campos: MargenGanancias,
  },
  {
    id: "HistorialDeCaja",
    nombre: "Historial de Caja",
    campos: HistorialDeCaja,
  },
];
